import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { jsonLdScriptProps } from "@/lib/json-ld";
import { SITE } from "@/lib/site";
import StickyBookButton from "@/components/StickyBookButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Site-wide LocalBusiness identity — keep in sync with SITE in src/lib/site.ts.
const localBusinessJsonLd = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "@id": "https://www.signatureclosets.com/#business",
  name: "Signature Closets",
  url: "https://www.signatureclosets.com",
  telephone: SITE.phoneJsonLd,
  priceRange: "$$",
  address: {
    "@type": "PostalAddress",
    ...SITE.addressParts,
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: SITE.coordinates.lat,
    longitude: SITE.coordinates.lng,
  },
  openingHoursSpecification: SITE.openingHoursSpecification,
  areaServed: "Benton City, WA and surrounding areas",
  sameAs: [SITE.instagramUrl],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Set by middleware.ts when it's rewriting a gated request to the Coming
  // Soon placeholder — hide site chrome like the sticky button in that case.
  const headersList = await headers();
  const showingComingSoon = headersList.get("x-showing-coming-soon") === "1";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={jsonLdScriptProps(localBusinessJsonLd)}
        />
        {children}
        {!showingComingSoon && <StickyBookButton />}
      </body>
    </html>
  );
}
